name: kahoot
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libgomp=15.2.0=h767d61c_6
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - altgraph==0.17.5
      - annotated-types==0.7.0
      - anyio==4.11.0
      - click==8.3.0
      - fastapi==0.118.0
      - h11==0.16.0
      - httptools==0.6.4
      - idna==3.10
      - linkify-it-py==2.0.3
      - markdown-it-py==4.0.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - packaging==25.0
      - platformdirs==4.4.0
      - plotext==5.3.2
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyinstaller==6.17.0
      - pyinstaller-hooks-contrib==2025.10
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      - rich==14.1.0
      - sniffio==1.3.1
      - starlette==0.48.0
      - textual==6.2.1
      - textual-plotext==1.0.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uc-micro-py==1.0.3
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
